import "dotenv/config";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "./generated/prisma/client";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const db = new PrismaClient({ adapter });

const EXTRA_PRODUCTS = [
  // ─── Café (prod_037–043) ──────────────────────────────────────────────────
  { id: "prod_037", sellerId: "seller_005", name: "Café Geisha Panamá",           description: "El café más codiciado del mundo. Notas de jazmín, melocotón y té negro. Tueste claro de precisión.",                                   categories: ["café"],             price: 9800,  stock: 12, unit: "100G / GRANO",    imageUrl: null, location: "Boquete, Panamá",        isLimitedEdition: true,  badge: "EDICIÓN RARA"      },
  { id: "prod_038", sellerId: "seller_005", name: "Cold Brew Concentrado",         description: "Extracción en frío de 24 horas con arábica de Colombia. Listo para diluir 1:1 con agua o leche. Sin acidez.",                            categories: ["café"],             price: 4200,  stock: 35, unit: "500ML",           imageUrl: null, location: "Colombia",                isLimitedEdition: false                    },
  { id: "prod_039", sellerId: "seller_005", name: "Café Descafeinado Swiss Water", description: "Proceso Swiss Water sin solventes. 99.9% sin cafeína. Conserva todos los sabores del arábica de origen.",                                 categories: ["café"],             price: 3900,  stock: 28, unit: "250G / MOLIDO",   imageUrl: null, location: "Brasil",                  isLimitedEdition: false                    },
  { id: "prod_040", sellerId: "seller_005", name: "Café Robusta Vietnam",          description: "Robusto y terroso con notas de cacao. Ideal para espresso italiano clásico o café con leche condensada.",                                  categories: ["café"],             price: 2800,  stock: 50, unit: "500G / MOLIDO",   imageUrl: null, location: "Dak Lak, Vietnam",       isLimitedEdition: false                    },
  { id: "prod_041", sellerId: "seller_005", name: "Espresso Ristretto Blend",      description: "Mezcla de 4 orígenes para extracción corta. Cuerpo denso, dulzura de dátil y crema persistente.",                                        categories: ["café"],             price: 5100,  stock: 40, unit: "250G / GRANO",    imageUrl: null, location: "Italia / Colombia",       isLimitedEdition: false                    },
  { id: "prod_042", sellerId: "seller_005", name: "Café Honey Process Costa Rica", description: "Proceso honey de Costa Rica, mucílago parcialmente retenido. Dulzor de miel de caña, body medio y acidez brillante.",                    categories: ["café"],             price: 6800,  stock: 18, unit: "250G / GRANO",    imageUrl: null, location: "Tarrazú, Costa Rica",     isLimitedEdition: true,  badge: "LOTE ESPECIAL"     },
  { id: "prod_043", sellerId: "seller_005", name: "Café Sumatra Mandheling",       description: "Proceso húmedo indonesio. Notas de tierra, cedro y cacao oscuro. Cuerpo pleno y bajo en acidez.",                                        categories: ["café"],             price: 5600,  stock: 22, unit: "250G / GRANO",    imageUrl: null, location: "Sumatra, Indonesia",     isLimitedEdition: false                    },

  // ─── Máquinas (prod_044–054) ──────────────────────────────────────────────
  { id: "prod_044", sellerId: "seller_005", name: "AeroPress Original",            description: "El método más versátil del mundo. Produce espresso concentrado o americano suave en menos de 2 minutos. Liviano y viajero.",               categories: ["máquinas", "café"], price: 7200,  stock: 30, unit: "COMPLETO",        imageUrl: null, location: "Buenos Aires, Argentina", isLimitedEdition: false                    },
  { id: "prod_045", sellerId: "seller_005", name: "Pour Over V60 Hario",           description: "Dripper cónico de cerámica para filtrado preciso. El favorito de baristas profesionales. Requiere filtros de papel.",                    categories: ["máquinas", "café"], price: 4500,  stock: 25, unit: "TAZA 1–4",        imageUrl: null, location: "Buenos Aires, Argentina", isLimitedEdition: false                    },
  { id: "prod_046", sellerId: "seller_005", name: "Kalita Wave 185",               description: "Dripper de fondo plano con 3 orificios. Extracción uniforme y consistente. Produce un café limpio y equilibrado.",                       categories: ["máquinas", "café"], price: 5200,  stock: 20, unit: "TAZA 2–4",        imageUrl: null, location: "Buenos Aires, Argentina", isLimitedEdition: false                    },
  { id: "prod_047", sellerId: "seller_005", name: "Cafetera de Goteo 1.5L",        description: "Goteo automático con placa calefactora y jarra de vidrio. Ideal para preparar café para toda la familia.",                               categories: ["máquinas", "café"], price: 12000, stock: 18, unit: "1.5L / 12 TAZAS", imageUrl: null, location: "Buenos Aires, Argentina", isLimitedEdition: false                    },
  { id: "prod_048", sellerId: "seller_005", name: "Máquina Espresso Semiautomática",description: "Bomba de 15 bares, vaporizador de leche y calentador termoblock. Para espresso de café de especialidad en casa.",                      categories: ["máquinas", "café"], price: 65000, stock: 8,  unit: "220V",            imageUrl: null, location: "Buenos Aires, Argentina", isLimitedEdition: false                    },
  { id: "prod_049", sellerId: "seller_005", name: "Sifón de Café 5 Tazas",         description: "Método de vacío japonés. Produce un café de extraordinaria claridad y perfume. Incluye filtro de tela y soporte.",                      categories: ["máquinas", "café"], price: 18500, stock: 10, unit: "5 TAZAS",         imageUrl: null, location: "Buenos Aires, Argentina", isLimitedEdition: true,  badge: "ÚLTIMAS UNIDADES" },
  { id: "prod_050", sellerId: "seller_005", name: "Balanza Digital Barista",        description: "Precisión de 0.1g con temporizador incorporado. Indispensable para extracción repetible. Superficie impermeable.",                      categories: ["máquinas", "accesorios"], price: 9500, stock: 22, unit: "2KG / 0.1G",  imageUrl: null, location: "Buenos Aires, Argentina", isLimitedEdition: false                    },
  { id: "prod_051", sellerId: "seller_005", name: "Tamper 58mm Acero",             description: "Pisón de acero inoxidable 58mm con base plana. Peso perfectamente balanceado para un prensado uniforme.",                                categories: ["máquinas", "accesorios"], price: 6800, stock: 30, unit: "58MM",        imageUrl: null, location: "Buenos Aires, Argentina", isLimitedEdition: false                    },
  { id: "prod_052", sellerId: "seller_005", name: "Moka Express 6 Tazas",          description: "La clásica cafetera italiana en versión familiar. Aluminio fundido, válvula de seguridad, produce 300ml de espresso intenso.",           categories: ["máquinas", "café"], price: 11000, stock: 28, unit: "6 TAZAS",         imageUrl: null, location: "Buenos Aires, Argentina", isLimitedEdition: false                    },
  { id: "prod_053", sellerId: "seller_005", name: "Filtros V60 Blanqueados x100",  description: "Filtros de papel sin sabor para dripper V60 talla 02. Lavados para eliminar el gusto a papel. Pack de 100 unidades.",                  categories: ["máquinas", "accesorios"], price: 1800, stock: 80, unit: "x100",       imageUrl: null, location: "Buenos Aires, Argentina", isLimitedEdition: false                    },
  { id: "prod_054", sellerId: "seller_005", name: "AeroPress Go — Viajero",        description: "Versión compacta del AeroPress original. Con taza-tapa y bolsa de tela. El compañero ideal para viajes y trabajo remoto.",               categories: ["máquinas", "café"], price: 8900,  stock: 15, unit: "COMPLETO",        imageUrl: null, location: "Buenos Aires, Argentina", isLimitedEdition: false                    },
];

async function main() {
  for (const p of EXTRA_PRODUCTS) {
    await db.product.upsert({ where: { id: p.id }, create: p as never, update: p as never });
  }
  console.log(`Upserted ${EXTRA_PRODUCTS.length} products.`);
  console.log(`  café section:    ~16 products (2 pages)`);
  console.log(`  máquinas section: ~14 products (2 pages)`);
}

main().catch(console.error).finally(() => db.$disconnect());
