import { NextResponse } from "next/server";
import type { SellerProduct } from "@/lib/services/externalApis";

// Mock endpoint — mirrors GET /api/seller/products from the Seller App contract.
// Active in dev when SELLER_API_URL=http://localhost:3000.
// Returns 404 in production to prevent accidental exposure.
export async function GET() {
  if (process.env.NODE_ENV === "production") {
    return NextResponse.json({ error: "Not found" }, { status: 404 });
  }

  const products: SellerProduct[] = [
    {
      id: "prod_001",
      sellerId: "seller_001",
      name: "Yerba Mate Rosamonte Especial",
      description: "Yerba mate suave y equilibrada, ideal para cebar mate largo. Elaborada en Corrientes.",
      categories: ["yerba mate", "infusiones"],
      price: 2850,
      stock: 120,
      unit: "500G",
      imageUrl: "https://http2.mlstatic.com/D_NQ_NP_654535-MLA92396918908_092025-O.webp",
      location: "Corrientes, Argentina",
      isLimitedEdition: true,
      badge: "LOTE ESPECIAL",
    },
    {
      id: "prod_002",
      sellerId: "seller_001",
      name: "Yerba Mate CBSé Energía Pomelo",
      description: "Yerba con extracto de pomelo y guaraná. Sabor cítrico refrescante.",
      categories: ["yerba mate", "saborizadas", "infusiones"],
      price: 3100,
      stock: 85,
      unit: "500G",
      imageUrl: "https://http2.mlstatic.com/D_NQ_NP_927424-MLU72565713266_112023-O.webp",
      location: "Corrientes, Argentina",
    },
    {
      id: "prod_003",
      sellerId: "seller_002",
      name: "Mate Calabaza Imperial Curado",
      description: "Mate artesanal curado con yerba, metal plateado.",
      categories: ["mates", "accesorios"],
      price: 4500,
      stock: 30,
      unit: "250ML",
      imageUrl: "https://acdn-us.mitiendanube.com/stores/005/262/890/products/imp1-539d6d4d80116ffbce17316867237631-640-0.webp",
      location: "Buenos Aires, Argentina",
      isLimitedEdition: true,
      badge: "ÚLTIMAS UNIDADES",
    },
    {
      id: "prod_004",
      sellerId: "seller_002",
      name: "Bombilla Acero Inoxidable Pico de Loro",
      description: "Filtro superior, tubo recto, apta para lavavajillas.",
      categories: ["bombillas", "accesorios"],
      price: 1200,
      stock: 200,
      unit: "ACERO INOX",
      imageUrl: "https://acdn-us.mitiendanube.com/stores/004/274/329/products/pico-de-loro-acero-1-d208ed4b8e792db12617592794656043-1024-1024.webp",
      location: "Buenos Aires, Argentina",
    },
    {
      id: "prod_005",
      sellerId: "seller_003",
      name: "Termo Stanley Classic Verde",
      description: "Vacío doble pared, mantiene temperatura 24h. Original USA.",
      categories: ["termos", "accesorios"],
      price: 28000,
      stock: 15,
      unit: "1L",
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQvAwrS7ZrOMVhlT5P3R-Jl87w46X7PWJ5vWg&s",
      location: "Ciudad Autónoma de Buenos Aires",
    },
    {
      id: "prod_006",
      sellerId: "seller_003",
      name: "Té Verde Taragüi Menta Poleo",
      description: "Saquitos de té verde con menta poleo, antioxidante natural.",
      categories: ["tés", "infusiones"],
      price: 890,
      stock: 300,
      unit: "x20 SAQUITOS",
      imageUrl: "https://statics.dinoonline.com.ar/imagenes/large_460x460/2020123_l.jpg",
      location: "Entre Ríos, Argentina",
      isLimitedEdition: true,
      badge: "LOTE ESPECIAL",
    },
    {
      id: "prod_007",
      sellerId: "seller_002",
      name: "Set Mate + Bombilla Artesanal",
      description: "Combo mate de madera pintada + bombilla alpaca. Ideal para regalo.",
      categories: ["mates", "accesorios", "combos"],
      price: 5800,
      stock: 5,
      unit: "SET COMPLETO",
      imageUrl: "https://acdn-us.mitiendanube.com/stores/003/024/004/products/img_5168-877e4a2f4754a8696517423171106674-480-0.webp",
      location: "Buenos Aires, Argentina",
      isLimitedEdition: true,
      badge: "ÚLTIMAS UNIDADES",
    },
    {
      id: "prod_008",
      sellerId: "seller_004",
      name: "Hierbas para Tereré Frío",
      description: "Mezcla de hierbas medicinales para preparar tereré frío tradicional.",
      categories: ["tereré", "infusiones"],
      price: 1650,
      stock: 0,
      unit: "300G",
      imageUrl: "https://jesper.com.ar/wp-content/uploads/2023/04/te-verde-terere-bolsa500g.jpg",
      location: "Misiones, Argentina",
    },
    {
      id: "prod_009",
      sellerId: "seller_005",
      name: "Café Yirgacheffe Etiopía",
      description: "Notas florales de jazmín y limón, acidez brillante. Perfil de tueste claro.",
      categories: ["café"],
      price: 4800,
      stock: 40,
      unit: "250G / GRANO",
      imageUrl: "https://newsite.fazenda.com.ar/wp-content/uploads/2025/01/Cafe-Ethiopia-La-fazenda.webp",
      location: "Etiopía",
      isLimitedEdition: true,
      badge: "LOTE ESPECIAL",
    },
    {
      id: "prod_010",
      sellerId: "seller_005",
      name: "Espresso Blend Brasileño",
      description: "Cuerpo intenso con notas de chocolate y frutos secos. Equilibrado y dulce.",
      categories: ["café"],
      price: 3600,
      stock: 60,
      unit: "1KG / MOLIDO",
      imageUrl: "https://www.connectroasters.com/cdn/shop/files/Connect112125-8.jpg?v=1763930646&width=1946",
      location: "Minas Gerais, Brasil",
      isLimitedEdition: true,
      badge: "ÚLTIMAS UNIDADES",
    },
    {
      id: "prod_011",
      sellerId: "seller_005",
      name: "Café Sidamo Etiopía Natural",
      description: "Proceso natural, notas de frutas rojas y chocolate oscuro. Tueste medio.",
      categories: ["café"],
      price: 5200,
      stock: 20,
      unit: "250G / GRANO",
      imageUrl: "https://newsite.fazenda.com.ar/wp-content/uploads/2025/01/Cafe-Ethiopia-La-fazenda.webp",
      location: "Etiopía",
      isLimitedEdition: true,
      badge: "EDICIÓN RARA",
    },
    {
      id: "prod_012",
      sellerId: "seller_001",
      name: "Yerba Mate Amanda Premium Reserva",
      description: "Cosecha tardía de hojas seleccionadas, estacionada 24 meses. Perfil intenso.",
      categories: ["yerba mate", "infusiones"],
      price: 4200,
      stock: 18,
      unit: "500G",
      imageUrl: "https://http2.mlstatic.com/D_NQ_NP_654535-MLA92396918908_092025-O.webp",
      location: "Corrientes, Argentina",
      isLimitedEdition: true,
      badge: "EDICIÓN RARA",
    },
  ];

  return NextResponse.json({ products });
}
